// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZepXbX28uehz-bV2UZdnnRv0EAH2mUk',
    appId: '1:498075473311:web:002ae6bbd999531865d9aa',
    messagingSenderId: '498075473311',
    projectId: 'babymonitor-2cc90',
    authDomain: 'babymonitor-2cc90.firebaseapp.com',
    storageBucket: 'babymonitor-2cc90.firebasestorage.app',
    measurementId: 'G-LNKVHYXKC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrM3WVpNDTrOjmtKN87wjnyn1HT3ctNlU',
    appId: '1:498075473311:android:a25d2e056b42bb8365d9aa',
    messagingSenderId: '498075473311',
    projectId: 'babymonitor-2cc90',
    storageBucket: 'babymonitor-2cc90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuAblML0ZiGFl1ZwlNXwW1UXnfDq-lds4',
    appId: '1:498075473311:ios:1834ba936357641d65d9aa',
    messagingSenderId: '498075473311',
    projectId: 'babymonitor-2cc90',
    storageBucket: 'babymonitor-2cc90.firebasestorage.app',
    iosBundleId: 'com.cagnaz.babymonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuAblML0ZiGFl1ZwlNXwW1UXnfDq-lds4',
    appId: '1:498075473311:ios:d34237a2b417dda165d9aa',
    messagingSenderId: '498075473311',
    projectId: 'babymonitor-2cc90',
    storageBucket: 'babymonitor-2cc90.firebasestorage.app',
    iosBundleId: 'com.example.babyMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnZepXbX28uehz-bV2UZdnnRv0EAH2mUk',
    appId: '1:498075473311:web:faf6a910ae3bdaf865d9aa',
    messagingSenderId: '498075473311',
    projectId: 'babymonitor-2cc90',
    authDomain: 'babymonitor-2cc90.firebaseapp.com',
    storageBucket: 'babymonitor-2cc90.firebasestorage.app',
    measurementId: 'G-4NW3XNJMBP',
  );
}
